services:
  - type: static
    name: satvik-foods-frontend-qa
    env: node
    region: oregon
    plan: starter
    buildCommand: NODE_ENV=development npm ci && VITE_ENVIRONMENT=test npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_BACKEND_API_URL
        value: https://satvik-foods-service-qa.onrender.com
      - key: VITE_ENVIRONMENT
        value: test
      - key: VITE_DATA_SOURCE
        value: backend
      - key: VITE_SANITY_PROJECT_ID
        sync: false
      - key: VITE_SANITY_DATASET
        value: products
      - key: VITE_SANITY_TOKEN
        sync: false

